### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ghost** [Aivean/royalroad-downloader#1]
Returns following when command is entered.

> Exception
> 
>  in thread "main" java.util.NoSuchElementException
>         at java.util.ArrayList$Itr.next(Unknown Source)
>         at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
>         at scala.collection.IterableLike$class.head(IterableLike.scala:107)
>         at scala.collection.AbstractIterable.head(Iterable.scala:54)
>         at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$4.apply(HtmlExtractor.scala:89)
>         at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$4.apply(HtmlExtractor.scala:89)
>         at net.ruippeixotog.scalascraper.scraper.SimpleExtractor.extract(HtmlExtractor.scala:63)
>         at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps$$anonfun$extract$1.apply(ScrapingOps.scala:16)
>         at scalaz.Monad$$anonfun$map$1$$anonfun$apply$2.apply(Monad.scala:14)
>         at scalaz.IdInstances$$anon$1.point(Id.scala:18)
>         at scalaz.Monad$$anonfun$map$1.apply(Monad.scala:14)
>         at scalaz.IdInstances$$anon$1.bind(Id.scala:20)
>         at scalaz.Monad$class.map(Monad.scala:14)
>         at scalaz.IdInstances$$anon$1.map(Id.scala:17)
>         at scalaz.syntax.FunctorOps.map(FunctorSyntax.scala:9)
>         at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.extract(ScrapingOps.scala:16)
>         at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$greater$greater(ScrapingOps.scala:20)
>         at com.aivean.royalroad.Main$$anonfun$4.apply(Main.scala:37)
>         at com.aivean.royalroad.Main$$anonfun$4.apply(Main.scala:34)
>         at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
>         at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
>         at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
>         at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
>         at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
>         at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
>         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
>         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
>         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
>         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
>         at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by Aivean** [comment]
@xd1986k thanks for reporting the issue.
I published [new release](https://github.com/Aivean/royalroadl-downloader/releases/tag/1.1) that should work for current RoyalRoad format. 

In case something breaks in the future, I [added command line arguments](https://github.com/Aivean/royalroadl-downloader#troubleshooting) that allow to override CSS selectors used by the parser.
