### ISSUE TITLE
Domain name changed

### ISSUE THREAD

**Issue by jcasey609** [Aivean/royalroad-downloader#14]
Just letting you know that the domain name for RoyalroadL has changed to https://www.royalroad.com/. You might want to make the required updates to the downloader.

**Comment by Aivean** [comment]
Will do. Thank you!

**Comment by CamilleHbp** [comment]
Any news? :) Thanks for the work!

**Comment by Aivean** [comment]
Sorry for the delay.

Check out the new release with updated domain:
https://github.com/Aivean/royalroad-downloader/releases/tag/2.0.0

Also, repository is renamed accordingly.
