### ISSUE TITLE
Unable to access file.

### ISSUE THREAD

**Issue by Radrahil** [Aivean/royalroad-downloader#19]
I apologise in advance. This happens and I don't know how to fix this,
![image](https://user-images.githubusercontent.com/54015030/96406085-55921580-11fc-11eb-90df-56b0dce04153.png)

**Comment by Aivean** [comment]
@Radrahil , I don't think that it's an app-specific issue.

You can try different [suggestions from here](https://stackoverflow.com/questions/11943948/what-causes-unable-to-access-jarfile-error).

**Comment by Radrahil** [comment]
Then this happens, and I don't see any file appearing in the Jar file's directory.
![image](https://user-images.githubusercontent.com/54015030/96407312-b7ec1580-11fe-11eb-9446-3348c7b7b036.png)

**Comment by Aivean** [comment]
Are you sure that the url you are using is correct?
I'm getting 404 trying to open https://www.royalroad.com/fiction/262534
