### ISSUE TITLE
[Feature Request] Confirmation on Book Title before immediate download

### ISSUE THREAD

**Issue by tristingreenstein** [Aivean/royalroad-downloader#26]
since the current version of this build has you type the 5 digit number instead of whole url, can you add a step between the first and immediate download to have it confirm the title of the book?

thanks! i love this tool

**Comment by Aivean** [comment]
Oops, haven't noticed the issue. 

> since the current version of this build has you type the 5 digit number instead of whole url,

That's not the case. You can input the whole url, like this:
`https://www.royalroad.com/fiction/55212/pyrebound`

or the url trimmed down to the **whole** number:
`https://www.royalroad.com/fiction/55212`

Hope that helps. Feel free to reopen if you have more questions.

**Comment by Aivean** [comment]
Updated the README to make it a bit more clear.
