### ISSUE TITLE
Error Validation

### ISSUE THREAD

**Issue by learn2learn1** [Aivean/royalroad-downloader#3]
This is the command I get when I try to use the .jar
[scallop] Error: Validation failure for 'fiction-link' option parameters: https://royalroadl.com/fiction/XXX

**Comment by Aivean** [comment]
@learn2learn1 how does the command that your try to run looks like?

If you just tried to run the jar without any parameters, then it's not how it suppose to work. Check the [How to Use](https://github.com/Aivean/royalroadl-downloader/blob/master/readme.md) section in readme.

**Comment by Aivean** [comment]
Just tried it myself:

```
royaldl_test2016-12-08_17.11.59 $ wget https://github.com/Aivean/royalroadl-downloader/releases/download/1.2.0/royalroadl-downloader-assembly-1.2.0.jar
....
2016-12-08 17:12:19 (3.11 MB/s) - 'royalroadl-downloader-assembly-1.2.0.jar' saved [39678256/39678256]
royaldl_test2016-12-08_17.11.59 $
royaldl_test2016-12-08_17.11.59 $ java -jar royalroadl-downloader-assembly-1.2.0.jar http://royalroadl.com/fiction/1234
Title: The Mansion | RoyalRoadL
parsing: http://royalroadl.com/fiction/chapter/9007
parsing: http://royalroadl.com/fiction/chapter/9151
Saving as: The_Mansion_RoyalRoadL.html
done
royaldl_test2016-12-08_17.11.59 $ ls -l
total 77560
-rw-r--r--  1 Aivean  staff     28079 Dec  8 17:12 The_Mansion_RoyalRoadL.html
-rw-r--r--  1 Aivean  staff  39678256 Oct 14 20:56 royalroadl-downloader-assembly-1.2.0.jar
royaldl_test2016-12-08_17.11.59 $
royaldl_test2016-12-08_17.11.59 $ less The_Mansion_RoyalRoadL.html
```

Closing issue for now. Feel free to reopen if you still can't make it work.

**Comment by learn2learn1** [comment]
This is what happens when I run it. I am not exactly sure what "parameters" mean, is that the command line argument thing? "java -jar my.jar [argument] ?
![mintty_2016-12-10_18-46-15](https://cloud.githubusercontent.com/assets/24466113/21077201/4285ad02-bf09-11e6-89ab-0f60ae222206.jpg)

I renamed the .jar to Royalroadl.jar.

**Comment by Aivean** [comment]
@learn2learn1 ah, I see the problem. Program expects url with `http` protocol (not `https`). I'll update it to accept https, meanwhile you can work around the issue by replacing `https` in your link with `http`.

**Comment by learn2learn1** [comment]
Alright thank you.
