### ISSUE TITLE
[Feature Request] Option to disable converting to data URIs

### ISSUE THREAD

**Issue by TadaCZE** [Aivean/royalroad-downloader#31]
The behavior of downloading images and embedding them into the document is useful in some situations, but not all of them. It would in some situations be more useful to leave the links as is or download the images into a folder and link to them.

**Comment by TadaCZE** [comment]
An option not to include images at all would also be a good idea.

**Comment by Aivean** [comment]
Out of curiosity, could you please list some of those situations? When implementing this feature I considered making it optional (which is not hard to do), but couldn't think of any specific compelling argument to do so.

I mean, technically, it swells the size of the html and takes a bit longer to download the book, but these effects seem to be negligent, unless I'm missing something.

Anyway, I'll get to implementing the option at some point, meanwhile you can use the previous version as a workaround.
