### ISSUE TITLE
[Bug] Embed images does not actually embed images

### ISSUE THREAD

**Issue by BinaryCPG** [Aivean/royalroad-downloader#36]
I was checking why the embedded images do not render for me.
During that I noticed that the embedded images were of type "data:text/html" and not a variation of "data:image/"

Attached is an example of the originally downloaded file with RR-downloader and the decoded base64 data.
[rrtest.zip](https://github.com/Aivean/royalroad-downloader/files/15050977/rrtest.zip)
It seems that instead of embedding the image an Imgur embed HTML page was generated with Google & FB tracking included?

TLDR: Image embedding embeds a reference html page for Imgur instead of the image data

**Comment by Aivean** [comment]
What's the original img url? Are you sure it's not dead?

**Comment by BinaryCPG** [comment]
Sorry, forgot to include the non-embedded version
Non-embedded the line resolves like this:
 `<p class="cnM3Njg3MGI5Y2RjYTRmMWY4MGY3YTE1NmUxNzkzZTIx"><span style="font-weight: 400"><img style="display: block; margin-left: auto; margin-right: auto" src="https://i.imgur.com/kp112Ad.png" alt="" width="1012" height="569"></span></p> `

The image is still there, at least for me: i.imgur.com/kp112Ad.png

**Comment by Aivean** [comment]
should be fixed in [2.10.1](https://github.com/Aivean/royalroad-downloader/releases/tag/v2.10.1)
