### ISSUE TITLE
[Feature Request] Ignore "Unauthorized content usage" text

### ISSUE THREAD

**Issue by VantianKaq** [Aivean/royalroad-downloader#39]
Is there any chance that the downloader could ignore paragraphs that contain the "Unauthorized content usage" warning?

**Comment by Aivean** [comment]
yes, use `--remove-warnings` flag

if a particular warning slips in, consider contributing to this keyword list:
https://github.com/Aivean/royalroad-downloader/blob/master/src/main/scala/com/aivean/royalroad/Utils.scala#L17

and the corresponding test
