### ISSUE TITLE
downloader not working anymore

### ISSUE THREAD

**Issue by coranark** [Aivean/royalroad-downloader#5]
I have used your downloader before and i like it. But when i tried using it today i got this message:
"Title: This Game We Call Life | RoyalRoadL
Saving as: This_Game_We_Call_Life_RoyalRoadL.html
done"
The story have 88 chapters and the html file created is 1kb large. I tried another story (10011) and i got the same result. then i switched to my laptop and got the same result on that to.
[This_Game_We_Call_Life_RoyalRoadL.txt](https://github.com/Aivean/royalroadl-downloader/files/1050867/This_Game_We_Call_Life_RoyalRoadL.txt)
I saved the html result as a txt file

**Comment by Aivean** [comment]
Thanks for reporting. I'll take a look.

**Comment by Aivean** [comment]
@coranark please check the latest release https://github.com/Aivean/royalroadl-downloader/releases/tag/1.2.2

**Comment by coranark** [comment]
it's working now thank you. :)
