### ISSUE TITLE
Validation failure

### ISSUE THREAD

**Issue by eyesonlyuploads** [Aivean/royalroad-downloader#6]
Hi, I've just tried to use this downloader on the site and I'm getting this error.

c:\rrld>java -jar royalroadl-downloader-assembly-1.2.2.jar http://royalroadl.com/fiction/5029/
[scallop] Error: Validation failure for 'fiction-link' option parameters: http://royalroadl.com/fiction/5029/

Is it something I'm doing wrong or has rrl changed there site. I've used this tool before without a problem.

**Comment by Aivean** [comment]
Thanks for reporting, I'll take a look.

**Comment by Aivean** [comment]
@eyesonlyuploads The problem is in the trailing slash in the fiction url. Remove it and it will pass the validation:
```
java -jar royalroadl-downloader-assembly-1.2.2.jar http://royalroadl.com/fiction/5029
```

I'll soon update the program to account for this case.

**Comment by eyesonlyuploads** [comment]
Wow, thank you didn't even this of that stupid me lol. Working fine now.

**Comment by Aivean** [comment]
No probs.
